"""initial migration

Revision ID: 3a2071315249
Revises:
Create Date: 2026-05-28 16:21:44.251839

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3a2071315249"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ar_records",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("customer_id", sa.String(), nullable=False),
        sa.Column("customer_name", sa.String(), nullable=True),
        sa.Column("customer_balance", sa.Float(), nullable=True),
        sa.Column("invoice_total", sa.Float(), nullable=True),
        sa.Column("invoice_applied_amount", sa.Float(), nullable=True),
        sa.Column("invoice_exchange_rate", sa.Float(), nullable=True),
        sa.Column("payment_total", sa.Float(), nullable=True),
        sa.Column("payment_applied_amount", sa.Float(), nullable=True),
        sa.Column("payment_exchange_rate", sa.Float(), nullable=True),
        sa.Column("credit_total", sa.Float(), nullable=True),
        sa.Column("credit_applied_amount", sa.Float(), nullable=True),
        sa.Column("credit_exchange_rate", sa.Float(), nullable=True),
        sa.Column("adjustment_total", sa.Float(), nullable=True),
        sa.Column("adjustment_applied_amount", sa.Float(), nullable=True),
        sa.Column("adjustment_exchange_rate", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ar_records_customer_id"), "ar_records", ["customer_id"], unique=False
    )
    op.create_table(
        "processed_records",
        sa.Column("invoice_id", sa.String(), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("invoice_id"),
    )
    op.create_index(
        op.f("ix_processed_records_idempotency_key"),
        "processed_records",
        ["idempotency_key"],
        unique=True,
    )
    op.create_table(
        "workflow_runs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("invoice_id", sa.String(), nullable=False),
        sa.Column("customer_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("current_stage", sa.String(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_runs_invoice_id"),
        "workflow_runs",
        ["invoice_id"],
        unique=True,
    )
    op.create_table(
        "workflow_stage_state",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("workflow_id", sa.String(), nullable=False),
        sa.Column("stage_name", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("output_json", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_stage_state_workflow_id"),
        "workflow_stage_state",
        ["workflow_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_workflow_stage_state_workflow_id"), table_name="workflow_stage_state"
    )
    op.drop_table("workflow_stage_state")
    op.drop_index(op.f("ix_workflow_runs_invoice_id"), table_name="workflow_runs")
    op.drop_table("workflow_runs")
    op.drop_index(
        op.f("ix_processed_records_idempotency_key"), table_name="processed_records"
    )
    op.drop_table("processed_records")
    op.drop_index(op.f("ix_ar_records_customer_id"), table_name="ar_records")
    op.drop_table("ar_records")
    # ### end Alembic commands ###
