"""your_message_here

Revision ID: 3cc46ebce382
Revises: 
Create Date: 2026-05-30 16:22:42.022995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc46ebce382'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ar_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('customer_balance', sa.Float(), nullable=True),
    sa.Column('invoice_total', sa.Float(), nullable=True),
    sa.Column('invoice_applied_amount', sa.Float(), nullable=True),
    sa.Column('invoice_exchange_rate', sa.Float(), nullable=True),
    sa.Column('payment_total', sa.Float(), nullable=True),
    sa.Column('payment_applied_amount', sa.Float(), nullable=True),
    sa.Column('payment_exchange_rate', sa.Float(), nullable=True),
    sa.Column('credit_total', sa.Float(), nullable=True),
    sa.Column('credit_applied_amount', sa.Float(), nullable=True),
    sa.Column('credit_exchange_rate', sa.Float(), nullable=True),
    sa.Column('adjustment_total', sa.Float(), nullable=True),
    sa.Column('adjustment_applied_amount', sa.Float(), nullable=True),
    sa.Column('adjustment_exchange_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id')
    )
    op.create_table('processed_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_records_idempotency_key'), 'processed_records', ['idempotency_key'], unique=True)
    op.create_table('workflow_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'COMPLETED', name='workflow_run_status'), nullable=False),
    sa.Column('current_stage', sa.Enum('INGESTION', 'MATCHING', 'VALIDATION', 'DECISION_ROUTING', name='workflow_stage_name'), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id')
    )
    op.create_table('workflow_stage_state',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('stage_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'COMPLETED', name='workflow_run_status'), nullable=False),
    sa.Column('output_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_stage_state_workflow_id'), 'workflow_stage_state', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_stage_state_workflow_id'), table_name='workflow_stage_state')
    op.drop_table('workflow_stage_state')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_processed_records_idempotency_key'), table_name='processed_records')
    op.drop_table('processed_records')
    op.drop_table('ar_records')
    op.drop_table('customers')
    # ### end Alembic commands ###
